name: Read
description: Looks up books information given an issue with the title of an ISBN.
runs:
  using: node16
  main: dist/index.js

inputs:
  readFileName:
    description: The file where you want to save your books.
    default: _data/read.yml
